language: node_js
node_js:
  - "stable"

notifications:
  email: false

cache:
  directories:
    - "node_modules"

services:
  - docker

install: npm install

branches:
  only:
  - master
  - develop

after_success:
  - echo "$PORT"
  - echo "$NODE_ENV"
  - docker build --build-arg NODE_ENV=${NODE_ENV} PORT=${PORT} -t henryqrm/hello .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push henryqrm/hello
