env:
  - PACKAGE_VERSION="1.0"

language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"

sudo: required

services:
  - docker

branches:
  only:
  - master

install: npm install

# script:
#   - npm run build

after_success:
  - docker build -t henryqrm/hello:$PACKAGE_VERSION .
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push henryqrm/hello:latest
