env:
  - PACKAGE_VERSION="1.1"

language: node_js
node_js:
  - "stable"

notifications:
  email: false

cache:
  directories:
    - "node_modules"

sudo: required

services:
  - docker

install: npm install

branches:
  only:
  - master
  - develop

# script:
#   - npm run build

after_success:
  - docker build -t henryqrm/hello:latest .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push henryqrm/hello:latest
