if: branch = master
env:
  PORT: 9000
  NODE_ENV: production

if: branch = develop
env:
  PORT: 8000
  NODE_ENV: development

language: node_js
node_js:
  - "stable"

notifications:
  email: false

cache:
  directories:
    - "node_modules"

services:
  - docker

install: npm install

branches:
  only:
  - master
  - develop

after_success:
  - docker build -t henryqrm/hello:$NODE_ENV --build-arg NODE_ENV=$NODE_ENV PORT=$PORT .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push henryqrm/hello:$NODE_ENV
